version: '3.8'

services:
  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: ${CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${PORTS}